[tool.poetry]
name = "coachhub_challenge"
version = "0.1.0"
description = "Technical challenge for the Machine Learning Engineer position at Coach Hub"
authors = ["Joao Guerreiro <joaoguerreiro779@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
transformers = "^4.12.2"

[tool.poetry.dev-dependencies]
pylint = ">=2.11.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
