name: Pipeline

on: [push]
env:
  APPLICATION_NAME: text_summarization_app
  SERVER_NAME: text_summarization_server
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@master
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip3 install poetry==1.1.11
        poetry config virtualenvs.create false
        poetry install
    - name: Build and tag image
      run: docker build -t "${{ secrets.DOCKER_HUB_USERNAME}}/${{ env.APPLICATION_NAME }}:latest" .
    - name: Spin up the service
      run: docker run -d -p 5000:3000 "${{ secrets.DOCKER_HUB_USERNAME}}/${{ env.APPLICATION_NAME }}:latest"
    - name: Run unit tests
      run: pytest -v -s -k test_classes.py
    - name: Push to DockerHub image registry
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME}}/${{ env.APPLICATION_NAME }}:latest